import { useEffect, useState } from "react";

const PROVIDERS = [["google", "Google services", "Gmail, Calendar, and Drive"], ["notion", "Notion", "Pages, notes, and meeting notes"]];

export default function ProductivityPlugins({ request }) {
  const [connections, setConnections] = useState([]); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  async function load() { try { setError(""); setConnections(await request("/productivity/connections")); } catch (loadError) { setError(loadError.message); } }
  useEffect(() => { load(); }, []);
  const connectionFor = (provider) => connections.find((item) => item.provider === provider);
  async function connect(provider) { try { setBusy(provider); setError(""); const result = await request(`/productivity/oauth/${provider}/authorize`, { method: "POST" }); window.open(result.authorization_url, "_blank", "noopener,noreferrer"); } catch (connectError) { setError(connectError.message); } finally { setBusy(""); } }
  async function disconnect(provider) { try { setBusy(provider); setError(""); await request(`/productivity/connections/${provider}`, { method: "DELETE" }); await load(); } catch (disconnectError) { setError(disconnectError.message); } finally { setBusy(""); } }
  async function sync(provider) { try { setBusy(provider); setError(""); await request(`/productivity/connections/${provider}/sync`, { method: "POST" }); await load(); } catch (syncError) { setError(syncError.message); } finally { setBusy(""); } }
  return <section className="rounded-md border border-white/10 bg-white/[0.04] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Productivity Plugins</h2><p className="mt-1 text-sm text-slate-300">Connect accounts locally. OAuth tokens use Windows DPAPI and are never shown here.</p></div><button className="rounded border border-white/15 bg-black/20 px-3 py-2 text-sm" onClick={load} type="button">Refresh status</button></div>{error && <p className="mt-3 text-sm text-red-200">{error}</p>}<div className="mt-5 grid gap-3 md:grid-cols-2">{PROVIDERS.map(([provider, title, description]) => { const connection = connectionFor(provider); const connected = connection?.connected; const working = busy === provider; return <article className="rounded border border-white/10 bg-black/20 p-4" key={provider}><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{title}</h3><p className="mt-1 text-xs text-slate-400">{description}</p></div><span className={`h-2.5 w-2.5 rounded-full ${connected ? "bg-emerald-400" : "bg-slate-500"}`} /></div><p className="mt-3 text-xs text-cyan-100">{connected ? `Connected: ${connection.account_email || "account"}` : "Not connected"}</p>{connection?.error && <p className="mt-2 text-xs text-red-200">{connection.error}</p>}<div className="mt-4 flex gap-3 text-xs">{connected ? <><button className="text-cyan-200" disabled={working} onClick={() => sync(provider)} type="button">{working ? "Working..." : "Sync"}</button><button className="text-red-200" disabled={working} onClick={() => disconnect(provider)} type="button">Disconnect</button></> : <button className="text-cyan-200" disabled={working} onClick={() => connect(provider)} type="button">{working ? "Working..." : "Connect"}</button>}</div></article>; })}</div><p className="mt-5 text-xs text-slate-400">Sending Gmail and deleting Drive files require a separate explicit confirmation on every request.</p></section>;
}
